IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'AssetDB')
BEGIN
	CREATE DATABASE AssetDB;
END
GO

USE AssetDB;
GO

-- CREATE SERVICETAG
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE name = 'SERVICETAG' and xtype = 'U')
BEGIN
	CREATE TABLE SERVICETAG (
		Id INT NOT NULL,
		Model VARCHAR(8) NOT NULL,
		CONSTRAINT PKST PRIMARY KEY (Id),
		CONSTRAINT UXServiceTag UNIQUE (Id)
	)
END
GO

-- CREATE UserID
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE name = 'USERID' and xtype = 'U')
BEGIN
	CREATE TABLE USERID (
		Id INT NOT NULL IDENTITY(1,1),
		EmployeeID VARCHAR(10) NOT NULL,
		FirstName VARCHAR(50) NOT NULL,
		LastName1 VARCHAR(50) NOT NULL,
		LastName2 VARCHAR(50) NOT NULL,
		ServiceTag INT NOT NULL,
		CONSTRAINT PKUerID PRIMARY KEY (Id),
		CONSTRAINT UXEmployeeID UNIQUE (EmployeeID),
		CONSTRAINT FKServiceTagUser FOREIGN KEY (ServiceTag) REFERENCES SERVICETAG (Id)
	)
END
Go

-- CREATE AssetEntry
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE name = 'ASSETS' and xtype = 'U')
BEGIN
	CREATE TABLE ASSETS (
		Id INT NOT NULL IDENTITY(1,1),
		Date DATETIME2(7) NOT NULL,
		EmployeeID INT NOT NULL,
		ServiceTag INT NOT NULL,
		CONSTRAINT PKAssets PRIMARY KEY (Id),
		CONSTRAINT FKAssetUserID FOREIGN KEY (EmployeeID) REFERENCES USERID (Id),
		CONSTRAINT FKAssetServiceTag FOREIGN KEY (ServiceTag) REFERENCES SERVICETAG (Id),
	)
END